CREATE TABLE PROGRAMADORES (
    PROGRA_CODIGO SERIAL NOT NULL,
    PROGRA_NOMBRE VARCHAR (25),
    PROGRA_APELLIDO VARCHAR (25),
    PROGRA_CORREO VARCHAR (50),
    PROGRA_DIRECCION VARCHAR (50),
    PROGRA_TELEFONO INTEGER,
    PROGRA_DEPENDENCIA VARCHAR (25),
    PROGRA_GENERO VARCHAR (20),
    PRIMARY KEY (PROGRA_CODIGO)
);